version: "3.8"
services:
  sql:
    image: postgres:latest
    environment:
      POSTGRES_USER: localdb
      POSTGRES_PASSWORD: localdb
      POSTGRES_DB: recipe
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  nosql:
    image: mongo:latest
    ports:
      - 27017:27017
